# Generated by Django 3.0.5 on 2020-11-30 02:46

from django.db import migrations, models
import django.db.models.manager
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201128_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSaves',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('company', models.CharField(default='unknown', max_length=255)),
                ('user_id', models.CharField(max_length=255)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
